name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up Java and sbt
      uses: guardian/setup-scala@v1

    - name: Run tests
      run: sbt test

      # Uploads information to the GitHub dependency graph to allow Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@f43202114d7522a4b233e052f82c2eea8d658134 # 3.2.1
