name: Update Dependency Graph
on:
  push:
    branches:
      - main
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK and Scala
        uses: guardian/setup-scala@v1

      # Uploads information to the GitHub dependency graph to allow Dependabot alerts for the repository
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@64084844d2b0a9b6c3765f33acde2fbe3f5ae7d3 # 3.1.0
